### ISSUE TITLE
Camera option not working in any version.

### ISSUE THREAD

**Issue by arunsheta** [artflutter/multi_image_picker2#1]
Multi picker is working well, but not able to capture image using the device camera.

**Comment by muriloventuroso** [comment]
I got this error on my android device:

```
W/System.err( 7471): java.io.IOException: Permission denied
W/System.err( 7471): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err( 7471): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
W/System.err( 7471): 	at java.io.File.createTempFile(File.java:2018)
W/System.err( 7471): 	at com.sangcomz.fishbun.util.CameraUtil.createImageFile(CameraUtil.java:64)
W/System.err( 7471): 	at com.sangcomz.fishbun.util.CameraUtil.takePicture(CameraUtil.java:31)
W/System.err( 7471): 	at com.sangcomz.fishbun.ui.picker.PickerController.takePicture(PickerController.java:41)
W/System.err( 7471): 	at com.sangcomz.fishbun.adapter.view.PickerGridAdapter$1.onClick(PickerGridAdapter.java:74)
W/System.err( 7471): 	at android.view.View.performClick(View.java:7307)
W/System.err( 7471): 	at android.view.View.performClickInternal(View.java:7284)
W/System.err( 7471): 	at android.view.View.access$3600(View.java:821)
W/System.err( 7471): 	at android.view.View$PerformClick.run(View.java:28053)
W/System.err( 7471): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err( 7471): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 7471): 	at android.os.Looper.loop(Looper.java:226)
W/System.err( 7471): 	at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err( 7471): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err( 7471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by jayeshindianic** [comment]
add ` android:requestLegacyExternalStorage="true"` this in you manifest.xml file, in your application tag.

**Comment by ankillashiva123** [comment]
> Multi picker is working well, but not able to capture image using the device camera.

Same issue here ? Any updates on this?
